#!/bin/bash

# install script

cd teensy_loader_cli
make
tlcpath=$(pwd)
echo "export PATH=$PATH:$tlcpath" >> ~/.bashrc
cd ..
teensypath=$(pwd)
echo "export PATH=$PATH:$teensypath" >> ~/.bashrc
source ~/.bashrc
exit
